[project]
name = "speaker-identification"
version = "0.1.0"
description = "Open-Set Speaker Identification for IAAA 2026 Competition"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click",
    "librosa",
    "matplotlib",
    "pandas",
    "pyyaml",
    "seaborn",
    "torch",
    "torchaudio",
    "torchcodec",
    "tqdm",
    "transformers",
    # MLOps & Deployment
    "zenml",
    "mlflow",
    "dagshub",
    "streamlit",
    "python-dotenv",
    "vastai",
    # Data Version Control (for DagsHub S3 remote)
    "dvc",
    "dvc-s3",
    "audiomentations>=0.43.1",
    "speechbrain>=1.1.0",
    "ruamel-yaml<0.18",
    "faiss-cpu>=1.15.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "black>=24.0.0",
    "ruff>=0.5.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
